name: Build and Publish JAR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -U clean package

      - name: Publish compiled JAR to repo (dist/)
        run: |
          set -e
          mkdir -p dist
          JAR=$(ls target/*.jar | head -n 1)
          echo "Found JAR: $JAR"
          cp "$JAR" dist/sql-webhook-solution.jar
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/sql-webhook-solution.jar
          # commit only if there are changes (avoid failing if file unchanged)
          if git diff --staged --quiet; then
            echo "No changes to commit (jar already up-to-date)."
          else
            git commit -m "CI: publish compiled JAR"
            git push
          fi
